### ISSUE TITLE
Tests fail with "redundant argument in sprintf" since 5.21.2

### ISSUE THREAD

**Issue by kentfredric** [dex4er/perl-Exception-Base#1]
Redundant argument in `sprintf` at `/tmp/loop_over_bdir-9818-9owfrp/Exception-Base-0.25-e2VGiB/blib/lib/Exception/Base.pm line 1615.`

http://www.cpantesters.org/cpan/report/71c40e56-0bfb-11e4-aeb4-166d0a370852 

https://metacpan.org/pod/release/ABIGAIL/perl-5.21.2/pod/perldelta.pod#New-Warnings
https://metacpan.org/pod/release/ABIGAIL/perl-5.21.2/pod/perldiag.pod#Redundant-argument-in-s

> Redundant argument in %s
> 
> (W redundant) You called a function with more arguments than other arguments you supplied indicated would be needed. Currently only emitted when a printf-type format required fewer arguments than were supplied, but might be used in the future for e.g. "pack" in perlfunc.
> 
> The warnings category redundant is new. See also [`[RT #121025]`](https://rt.perl.org/Public/Bug/Display.html?id=121025)

**Comment by andk** [comment]
_Ping_

Could we get a new release please? New perl is due every day now and all dependents of Exception::Base are not or not sufficiently tested with it.

Thanks,

**Comment by kentfredric** [comment]
This is kinda getting crazy with Exception::Base not being installable for almost a year now.

**Comment by icydee** [comment]
Is there a work-around for this? What are the consequences of doing a --force on install?

**Comment by veryrusty** [comment]
Having encountered this today, would love to see it fixed.

@dex4er Is there anything that can be done to help ?

**Comment by eserte** [comment]
A CPAN distroprefs file exist now for automatic patching of the distribution within CPAN.pm:
https://github.com/eserte/srezic-cpan-distroprefs/blob/master/Exception-Base.yml
